#!/bin/bash

# this is an over-ride script for the 'greyscale' script. This script will simply disable 'greyscale' another overide script 'greyscale-on' will be provided as an over-ride to manually enable greyscale aswell.
sed -i -E '/screen_shader/s/^( *)/\1#/' ~/dotfiles/hypr/hyprland.org && exec emacs --batch --eval "(progn (find-file \"~/dotfiles/hypr/hyprland.org\") (save-buffer) (org-babel-tangle))"  

# Reload hyprland
sleep 10
hyprctl reload
