#!/usr/bin/env bash

# Kill current waybar
killall waybar

# Load user's waybar config
if [[ $USER = "user" ]]; then
    # Check if Hyprland is running
    if pgrep -x "Hyprand" > /dev/null; then
	waybar -c ~/dotfiles/waybar/config.jsonc -s ~/.config/waybar/style.css & disown
	
    # Check if Sway is running
    elif pgrep -x "sway" > /dev/null; then
	waybar -c ~/dotfiles/swaybar-dracula/config.jsonc -s ~/dotfiles/swaybar-dracula/style.css & disown

    # Check if Niri is running
    elif pgrep -x "niri" > /dev/null; then
	waybar -c ~/dotfiles/niri-waybar/config.jsonc -s ~/dotfiles/niri-waybar/style.css & disown
	

    else
	waybar & disown
	echo "Waybar configuration not loaded for user '$USER'."
    fi
fi
# Rember this is a BASH script, so it will NOT work in Eshell
