#!/usr/bin/env bash

function exit_after(){
    kill -s SIGTERM "$YAD_PID" &> /dev/null
    $1
}
export -f exit_after

yad --form --title "HD's Theme Switcher and Override Tool" --height 420 --width 600 \
	--center --text-align "left" --window-icon="$HOME/Pictures/dev/emacs-desktop.png" \
	--borders 20 \
	--image="$HOME/Pictures/dev/emacs-desktop.png" \
	--text "<span font_weight='bold' font='18' color='#ff79c6'>Welcome to HD's Theme Switcher</span>

This program aims to provide a simple, and centralized location to change color themes and overrive various configurations for a Linux system using a tiling window manager (TWM) such as Sway or Hyprland." \
	--columns=2 --align-button \
	--field=" Waybar Theme Switcher!color! Change Waybar theme":fbtn "/home/$USER/.local/bin/theme-waybar" \
	--field=" Rofi Theme Switcher!color! Change Rofi theme":fbtn "/home/$USER/.local/bin/theme-rofi" \
	--field=" Disable Greyscale!color-mode-black-white! Override the scheduled greyscale function":fbtn "/home/$USER/.local/bin/greyscale-off" \
	--field=" Enable Greyscale!color-mode-black-white! Override the scheduled greyscale function":fbtn "/home/$USER/.local/bin/greyscale-on" \
	--field=" Enable bluelight filter!color-mode-hue-shift-positive! Override the scheduled blue-light function via hyprsunset.":fbtn "/home/$USER/.local/bin/blue-light-on" \
	--field=" Disable bluelight filter!color-mode-hue-shift-negative! Override the scheduled blue-light function via hyprsunset.":fbtn "/home/$USER/.local/bin/blue-light-off" \
	--field=" Reload Configs!task-recurring! Reload various programs to apply updated cusotm configurations":fbtn "/home/$USER/.local/bin/launch-waybar" \
	--button=" About!about!about overides-gui:yad --about --pname 'Overrides GUI' --authors 'Henry Davies' --license MIT" \
	--button=" Exit!exit!gtk-cancel:1" \


