#!/usr/bin/env bash

# kill any running emacsclient processes 
if pgrep -x "emacsclient" > /dev/null; then
    echo "Killing Emacs client connections..."
    echo ""
    killall emacsclient
else
    echo "No emacsclient processes found"
    echo ""
fi
# start the emacs server if no emacs processes found
if ! pgrep -f "emacs" > /dev/null; then
    echo "Starting Emacs daemon..."
    pkexec /usr/bin/emacs --daemon & disown
    echo "Launching Emacs client and connecting to newly established daemon..."
    /usr/bin/emacsclient -c -a "" "$@"

# Wait a few seconds then launch emacs
elif pgrep -f "emacs --daemon" > /dev/null; then
    echo "Launching Emacs client..."
    /usr/bin/emacsclient -c -a "" "$@"
elif pgrep -x "emacs" > /dev/null; then
    echo "Killing non daemon Emacs processes..."
    echo ""
    killall emacs
    echo "Starting Emacs daemon..."
    echo ""
    pkexec /usr/bin/emacs --daemon & disown
    echo "Launching Emacs client and connecting to newly established daemon..."
    echo ""
    /usr/bin/emacsclient -c -a "" "$@"
fi
